name: Deploy to GitHub Pages

on:
    # Trigger the workflow every time you push to the `main` branch
    # Using a different branch name? Replace `main` with your branch’s name
    push:
        branches: [main]
    # Allows you to run this workflow manually from the Actions tab on GitHub.
    workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout your repository using git
              uses: actions/checkout@v4.1.1

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8.15.6

            - name: Setup Node
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: 20.12.1
                  cache: pnpm

            - name: Install, build, and upload your site
              uses: withastro/action@v2.0.0
              with:
                  package-manager: pnpm@8.15.6

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4.0.5
